<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>datadriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a54d76b0-a4cd-41a8-8d83-37d8a8af8133</testSuiteGuid>
   <testCaseLink>
      <guid>fc84ad70-cc2d-423c-a881-9acd8fe522e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DataDrivenChk/loginNdlogout</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9f9b96ac-e393-4921-9f4a-fa2832247354</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/wsnames</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>8ff26508-9aab-437d-b178-4f1c9ab82b35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>d2a38ea4-6dea-478f-bcec-00f3fac369f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7bacdd1-37dc-40aa-a2ff-074eb344cc6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BenjaminBarker/UC1/UC1T3</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f280dc7e-5204-4f91-a478-9d74cebee433</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/wsnames</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d624b2b5-dd67-48bf-bcc7-1f58ad17e9af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09f4446a-a629-446a-9213-4b2476e52986</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07b38de0-4fc5-456b-ab06-757e4ca113b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c7c3b4-f5b2-437e-806b-9d5846c1cd03</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
