<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>WS-TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0a821f73-cd44-4a3e-8d1b-ea6ce9acd17b</testSuiteGuid>
   <testCaseLink>
      <guid>5f327f7f-e44e-432e-9368-5f831d998ca1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenChk/LoginCID008</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fd585fe2-a95d-4f81-be75-2b9cdc5c9cd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenChk/WScombos</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>148ffcfd-0063-4e90-bed5-f28d6938836c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TabularData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>148ffcfd-0063-4e90-bed5-f28d6938836c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>workspaceName</value>
         <variableId>a74c9407-b437-45d3-ab38-18b570e1c67c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22a1f797-567b-4992-ac23-6290374b0118</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bdce148-12f8-4a69-8e7b-ddf68511cad1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a0cf4de-7296-4f69-9a67-99647f502bb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>412d60da-18be-473d-80d7-0256141fa410</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>566259d0-face-4e81-ad98-7808f08bb824</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f66e7853-013c-42c6-b739-b934cea171c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>148ffcfd-0063-4e90-bed5-f28d6938836c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>rowFields</value>
         <variableId>6beccdbb-fed4-496d-bc82-fca322c26ea3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdd93d36-2aac-4baa-b15e-2a90a5211ba1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>148ffcfd-0063-4e90-bed5-f28d6938836c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>colFields</value>
         <variableId>028863ea-b042-4130-8fac-d0b323f9041f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>148ffcfd-0063-4e90-bed5-f28d6938836c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataFields</value>
         <variableId>3a1a8116-72dc-43ae-a242-c5d80efa61e0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
